// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BForm: typeof import('bootstrap-vue-3')['BForm']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RichTextEditor: typeof import('./my-app/src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TipTap: typeof import('./src/components/TipTap.vue')['default']
    WelcomeBlurb: typeof import('./src/components/WelcomeBlurb.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
